### PR TITLE
Use force_text instead of unicode (Python3 friendly)

### PR DESCRIPTION
**Pull request by vstoykov**

### CODE REVIEW

**Comment by mishbahr** [comment]
Good idea. Thanks @vstoykov

**Comment by mishbahr** [comment]
Will push to PyPi as soon as I can. Thanks!

**Comment by vstoykov** [comment]
Please let me know when you push to PyPi. Thanks a lot.

**Comment by mishbahr** [comment]
@vstoykov Pushed to PyPi https://pypi.python.org/pypi/djangocms-forms/0.2.2

**Pull request merged**
