### PR TITLE
Add placeholder to fields

### LINKED ISSUE #44: Add placeholder to some field types
We need add placeholder to some field types (eq: url or tel)

### PR DESCRIPTION
**Pull request by itcrab**
Fixes #44 

We added placeholder to all supported field types:
- number
- url
- password
- tel

### CODE REVIEW

**Comment by itcrab** [comment]
@mishbahr hi again) I add little functionality for more customizing

Please merge this PR

**Comment by itcrab** [comment]
@mishbahr ping

**Comment by itcrab** [comment]
@mishbahr please waiting - I want small refactoring

**Comment by itcrab** [comment]
@mishbahr done

**Comment by mishbahr** [comment]
I'm super busy. I'll have a look at this as soon as I can. Thanks

**Comment by itcrab** [comment]
@mishbahr ping

**Pull request merged**
