### PR TITLE
Validate if referrer was manupulated

### LINKED ISSUE #39: Error 500 when referrer is missing from cleaned data and request is not AJAX
When normal POST request was made (not an AJAX one) then the view is trying redirect the user back to the form URL pointed in `referrer` field. If for some reason this field is missing, then ERROR 500 is raised with `KeyError` about `referrer` missing from `cleaned_data`.

Some things that need to be done is to make this logic more "exception safe". Also from security standpoint there are things that probably should be done about restricting the values that can be posted for this value.

I will look at it to prepare a fix.

### PR DESCRIPTION
**Pull request by vstoykov**
Prevent Error 500 if referrer field is missing in the form and also prevent redirection to malicious URLs

Fixed #39

### CODE REVIEW

**Comment by mishbahr** [comment]
Thank you for your pull request. I would like a suggest a slightly different way .. following python DRY principle.

How about a `.get_redirect_url()`  method, that takes the form instance as an argument.
```
    def get_redirect_url(self, form, success=True):
        """
        Determine the URL to redirect to once the form is processed.
        """
        if success and form.redirect_url:
            # Forcing possible reverse_lazy evaluation
            return force_text(form.redirect_url)

        redirect_url = form.cleaned_data.get('referrer', None) or self.request.META.get('HTTP_REFERER', '')
        if is_safe_url(redirect_url, self.request.get_host()):
            return redirect_url

        # Failed to determine a valid url for redirection. Fall back to homepage.
        return '/'
```

And both `.form_valid()` and `.form_invalid()` can use the same method.

```
    def form_valid(self, form, *args, **kwargs):
        [...]
        return redirect(self.get_redirect_url(form, success=True))

    def form_invalid(self, form, *args, **kwargs):
        [...]
        return redirect(self.get_redirect_url(form, success=False))
```

**Comment by vstoykov** [comment]
I thought about same/similar thing but at the end I decided not to do it because there is slightly different logic in both cases.

1. When the form is correct but referrer field is malformed we will redirect the user to home page (which is not the best but I can't came with another idea)
2. When the form is invalid and the referrer field is malformed then we raise 404 and not send a message to the user (because they will never read it and we do not want to flood the messages store).

For that reason I thought that is better to not make a common function/method that will determine the URL for redirection.

**Comment by mishbahr** [comment]
>  flood the messages store

Valid point. Thanks for getting back to me.

Can you mark `Invalid referrer` as a translated string? i.e `_('Invalid referrer')`

Thanks

**Comment by vstoykov** [comment]
I've updated the PR.

**Comment by mishbahr** [comment]
I'll push it to PyPi as soon as I can.

**Comment by mishbahr** [comment]
Uploaded djangocms-forms-0.2.4 to PyPi.

**Comment by mishbahr** [comment]
Don't forget to star this repo 😎

**Pull request merged**
