### PR TITLE
Add feature set custom CSS class for any fields

### LINKED ISSUE #46: Need set CSS-class for fields
We strongly need feature set CSS-classes for any fields

### PR DESCRIPTION
**Pull request by itcrab**
Fixes #46

We added feature set custom CSS-classes for any fields

### CODE REVIEW

**Comment by itcrab** [comment]
@mishbahr hi again) I add little functionality for more customizing

Please merge this PR

**Comment by itcrab** [comment]
@mishbahr ping

**Comment by mishbahr** [comment]
Adding CSS classes is not something I would expect a CMS user/editor to handle.

`djangocms-forms` allows the developer to have different templates via `DJANGOCMS_FORMS_TEMPLATES` setting. This should be used to handle different layouts etc.

**Comment by itcrab** [comment]
@mishbahr it's not good because form is dynamic life - tomorrow customer may add one or two or N fields and we don't see this, but if he sets correctly css-classes all will be fine (fields mapped in custom grid). If we hard-coded css-classes in html-template we lost freedom for setup visualization fields in grid by design.

Small example: we have form with many fields and we prepare custom grid for it's places:
2 x 2
4
2 x 0
0 x 2

If we have functionality for sets css-classes we may do form better every day. As example we may change order rows or change width cells - it don't needed edit html-template.

**Pull request closed without merging**
